---
gobin:           "{{ ansible_env.HOME }}/go/bin/go{{ go_version }}"

witnessctl_bin:  "{{ ansible_env.HOME }}/go/bin/witnessctl"
litewitness_bin: "{{ ansible_env.HOME }}/go/bin/litewitness"
witness_dir:     "{{ ansible_env.HOME }}/witness"
witness_db:      "{{ witness_dir }}/litewitness.db"

litewitness_url: "filippo.io/torchwood/cmd/litewitness"
witnessctl_url:  "filippo.io/torchwood/cmd/witnessctl"

